### ISSUE TITLE
Problems with SSL TLSv1.3

### ISSUE THREAD

**Issue by SkullSplitter2020** [Chris-The-Tuner/diytelegrambot-php#1]
Hey :)

I have some Problems with SSL TLSv1.3 

With PostMan i got this Response:

`{
    "ok": true,
    "result": {
        "url": "https://DOMAIN.COM:PORT/TelegramBot/bot.php",
        "has_custom_certificate": false,
        "pending_update_count": 50,
        "last_error_date": 1639827081,
        "last_error_message": "SSL error {error:1409442E:SSL routines:ssl3_read_bytes:tlsv1 alert protocol version}",
        "max_connections": 40,
        "ip_address": "IP-ADRESS"
    }`

What can i do ?

Cheers

Skull

**Comment by Chris-The-Tuner** [comment]
This seems to be a issue with your webserver.
There is nothing my code can fix on that.
I always use NGINX with Certbot for my webservers and never had issues.
But if i remember you can get Telegram to recognize a custom (non "official" cert) on your server.
This should be well documented in their docs.
